name: linux

on:
  push:
    branches:
      - main

jobs:
  check-perl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        perl: [ '5.32', '5.30', '5.28' ]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: show perl version
        run: perl -V
      - name: syntax check
        run: perl -c svg-calendar.pl
