name: linux

on:
  push:
    branches:
      - main

jobs:
  check-perl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: syntax check
        run: perl -c svg-calendar.pl
